name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build the Docker image
        run: docker build ./my-app/my-app -t ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }}

      - name: Log in to Docker Registry
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login docker.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push the Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }}

      - name: Checkout code for the update
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Update Deployment Image Tag
        run: |
          sed -i "s|${{ secrets.DOCKER_USERNAME }}/my-app:.*|${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }}|g" ./my-app/manifests/react-deployment.yaml
          git config --global user.email "acdev22@outlook.fr"
          git config --global user.name "HanaAc22"
          git add .
          git commit -am "Update image tag to ${{ github.sha }}" || echo "No changes to commit"
          git push origin main